#! /bin/bash

T="$(date +%s)"
spark-submit \
--master yarn \
--deploy-mode cluster \
--name IPDeviceGraph \
--class com.soteradefense.dga.graphx.DGARunner \
--executor-cores 2 \
--num-executors 2 \
--executor-memory 2G \
--driver-memory 2G \
--files "conf/application.conf,conf/log4j.properties" \
lib/dga-graphx-0.1-all.jar "$@"

T="$(($(date +%s)-T))"
echo "Time in seconds: ${T}"